### ISSUE TITLE
Do not add prefix in last_active

### ISSUE THREAD

**Issue by hawkeye-7** [MediaWiki-Bot/MediaWiki-Bot#85] opened 2018-06-08 01:29 UTC
The use of the user: prefix in last_active is undocumented, and Wikimedia wants 

Change line 2371:
    $username = "User:$username" unless $username =~ /User:/i;
to:
    $username =~ s/User://i;

**Comment by wp-seth** [comment] 2021-09-25 22:03
duplicate of #84.

**Closed by wp-seth** 2021-09-25 22:03 UTC
